title: Chad Taylor
description: Stuff that I come across and find interesting.
author: Chad Taylor
email: ctatx1@gmail.com
phone: 512.422.6928
github: https://github.com/ctatx1
about: I am a Freelance Web Developer at Intelligent Works Design. I love working on backend and frontend technologies. #<a href="https://www.build.com" target="_blank">Build.com</a>*/ 
disqus_shortname: programming
#google_analytics: UA-31048387-6
avatar_url:"https://ctatx1.github.io//static/img/10350338_10204067694679999_7757015693539131175_n.jpg"
#/static/img/68536994.jpg
#ctatx1.github.io/static/img/68536994.jpg
enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/CTATX"
    - icon: fa-twitter
      link: "https://twitter.com/ctatx"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/chad-taylor-42ab3270/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/ctatx1"

share:
  twitter_username: ctatx
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: Tweets
      url: /tweets/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
#url: "https://tmjam.github.io/tauseef-blog"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
